[package]
name = "pledge"
version = "0.1.0"
description = "Pledge (Clock In): Sovereign Habit & Physical Proof-of-Action Staking Protocol on Solana Mobile"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "pledge"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "=1.18.26"
